name = "lustre_fable"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
lustre = { path = "../lustre" }
lustre_portal = ">= 1.0.0 and < 2.0.0"
modem = ">= 2.0.0 and < 3.0.0"

[dev_dependencies]
lustre_dev_tools = ">= 2.3.6 and < 3.0.0"
cog = ">= 2.0.3 and < 3.0.0"

[tools.lustre.dev]
watch = ["dev"]
