name = "lustre_fable"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
lustre = { git = "https://github.com/lustre-labs/lustre.git", ref = "main" }
lustre_portal = ">= 1.0.0 and < 2.0.0"
modem = ">= 2.0.0 and < 3.0.0"

[dev_dependencies]
gerbil = "1.0.0-rc4"
lustre_dev_tools = ">= 2.4.0 and < 3.0.0"
gleam_community_maths = ">= 2.0.2 and < 3.0.0"
gleam_time = ">= 1.11.0 and < 2.0.0"

[tools.lustre.dev]
watch = ["dev"]
